<?php

namespace Proxies\__CG__\PC\FundationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pet extends \PC\FundationBundle\Entity\Pet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'adoptions', 'photos', 'credits', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'id', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'name', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'age', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'species', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'race', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'colour', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'gender', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'isVacunated', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'isSterilized', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'status'];
        }

        return ['__isInitialized__', 'adoptions', 'photos', 'credits', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'id', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'name', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'age', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'species', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'race', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'colour', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'gender', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'isVacunated', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'isSterilized', '' . "\0" . 'PC\\FundationBundle\\Entity\\Pet' . "\0" . 'status'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', [$age]);

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecies($species)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecies', [$species]);

        return parent::setSpecies($species);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecies', []);

        return parent::getSpecies();
    }

    /**
     * {@inheritDoc}
     */
    public function setRace($race)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRace', [$race]);

        return parent::setRace($race);
    }

    /**
     * {@inheritDoc}
     */
    public function getRace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRace', []);

        return parent::getRace();
    }

    /**
     * {@inheritDoc}
     */
    public function setColour($colour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColour', [$colour]);

        return parent::setColour($colour);
    }

    /**
     * {@inheritDoc}
     */
    public function getColour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColour', []);

        return parent::getColour();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVacunated($isVacunated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVacunated', [$isVacunated]);

        return parent::setIsVacunated($isVacunated);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVacunated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVacunated', []);

        return parent::getIsVacunated();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSterilized($isSterilized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSterilized', [$isSterilized]);

        return parent::setIsSterilized($isSterilized);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSterilized()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSterilized', []);

        return parent::getIsSterilized();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhoto(\PC\FundationBundle\Entity\Photo $photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhoto', [$photo]);

        return parent::addPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function removePhoto(\PC\FundationBundle\Entity\Photo $photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePhoto', [$photo]);

        return parent::removePhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotos', []);

        return parent::getPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function addCredit(\PC\FundationBundle\Entity\Credit $credit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCredit', [$credit]);

        return parent::addCredit($credit);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCredit(\PC\FundationBundle\Entity\Credit $credit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCredit', [$credit]);

        return parent::removeCredit($credit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredits', []);

        return parent::getCredits();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdoption(\PC\FundationBundle\Entity\Adoption $adoption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdoption', [$adoption]);

        return parent::addAdoption($adoption);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdoption(\PC\FundationBundle\Entity\Adoption $adoption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdoption', [$adoption]);

        return parent::removeAdoption($adoption);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdoptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdoptions', []);

        return parent::getAdoptions();
    }

}
