<?php

namespace PC\FundationBundle\Repository;

/**
 * ApppetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApppetRepository extends \Doctrine\ORM\EntityRepository
{
}
