<?php

namespace PC\FundationBundle\Repository;

/**
 * AppuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppuserRepository extends \Doctrine\ORM\EntityRepository
{
}
