<?php

namespace PC\FundationBundle\Repository;

/**
 * CatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogRepository extends \Doctrine\ORM\EntityRepository
{
}
