<?php

namespace PC\FundationBundle\Repository;

/**
 * Census_collaboratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Census_collaboratorRepository extends \Doctrine\ORM\EntityRepository
{
}
