<?php

namespace PC\FundationBundle\Repository;

/**
 * CensusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CensusRepository extends \Doctrine\ORM\EntityRepository
{
}
