<?php

namespace PC\FundationBundle\Repository;

/**
 * ControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlRepository extends \Doctrine\ORM\EntityRepository
{
}
