<?php

namespace PC\FundationBundle\Repository;

/**
 * DonativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonativeRepository extends \Doctrine\ORM\EntityRepository
{
}
