<?php

namespace PC\FundationBundle\Repository;

/**
 * SterilizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SterilizationRepository extends \Doctrine\ORM\EntityRepository
{
}
