#--------------------------------------------------------------
#--- rutas de navegación     ----------------------------------
#--------------------------------------------------------------

pc_fundation_homepage:
    path:     /
    defaults: { _controller: PCFundationBundle:Main:index }

pc_fundation_comedogs:
    path:     /index/comedogs
    defaults: { _controller: PCFundationBundle:Main:comedogs }
 
pc_fundation_tapitas:
    path:     /index/tapitas
    defaults: { _controller: PCFundationBundle:Main:tapitas }
    
pc_fundation_adoptar:
    path:     /index/adoptar
    defaults: { _controller: PCFundationBundle:Main:adoptar }

pc_fundation_index:
    path:     /index
    defaults: { _controller: PCFundationBundle:Main:index }

pc_fundation_eventos:
    path:   /eventos
    defaults: { _controller: PCFundationBundle:Main:eventos }
    
pc_fundation_nosotros:
    path:     /nosotros
    defaults: { _controller: PCFundationBundle:Main:nosotros }

#--------------------------------------------------------------
#--- rutas del usuario ----------------------------------------
#--------------------------------------------------------------

pc_fundation_encuesta:
    path:     /encuesta
    defaults: { _controller: PCFundationBundle:Main:encuesta }
    
pc_user_encuesta:
    path:     /user/add/{petId}
    defaults: { _controller: PCFundationBundle:User:add }

pc_user_create:
    path:     /user/create/{petId}
    defaults: { _controller: PCFundationBundle:User:create }
    methods:  POST

#--------------------------------------------------------------
#--- rutas del administrador ----------------------------------
#--------------------------------------------------------------

pc_administrator_index:
    path:     /admin/
    defaults: { _controller: PCFundationBundle:Admin:index }

pc_administrator_login:
    path:     /admin/login
    defaults: { _controller: PCFundationBundle:Admin:login }
    
pc_administrator_logout:
    path:     /admin/logout
    defaults: { _controller: PCFundationBundle:Admin:logout }
    
pc_administrator_add:
    path:     /admin/add
    defaults: { _controller: PCFundationBundle:Admin:add }

pc_administrator_create:
    path:     /admin/create
    defaults: { _controller: PCFundationBundle:Admin:create }
    methods:  POST
    
pc_administrator_edit:
    path:     /admin/edit/{id}
    defaults: { _controller: PCFundationBundle:Admin:edit }
    
pc_administrator_update:
    path:     /admin/update/{id}
    defaults: { _controller: PCFundationBundle:Admin:update }   
    methods:  [POST, PUT]

pc_administrator_control:
    path:   /admin/control
    defaults: {_controller: PCFundationBundle:Admin:control }

pc_administrator_control_add:
    path:   /admin/control/add/{sterilizationId}
    defaults: {_controller: PCFundationBundle:Admin:controladd }  
    
pc_admininstrator_control_create:
    path:   /admin/control/create/{sterilizationId}
    defaults: {_controller: PCFundationBundle:Admin:createControl }
    methods: POST

#--------------------------------------------------------------
#---- rutas del administrador para censo y esterilización -----
#--------------------------------------------------------------

pc_admin_jornada_censo:
    path:     /admin/jornadacenso/view
    defaults: { _controller: PCFundationBundle:Admin:jornadacenso } 

pc_admin_jornada_censo_mas:
    path:     /admin/jornadacenso/mas/{meetingId}
    defaults: { _controller: PCFundationBundle:Admin:jornadacensomas }

pc_admin_jornada_censo_addcollaborator:
    path:     /admin/jornadacenso/addcollaborator/{meetingId}
    defaults: { _controller: PCFundationBundle:Admin:addcollaborator }

pc_admin_jornada_censo_create_collaborator:
    path:     /admin/jornadacenso/createcollaborator/{meetingId}
    defaults: { _controller: PCFundationBundle:Admin:createCollab }
    methods:  POST



pc_admin_jornada_censo_edit:
    path:     /admin/jornadacenso/edit
    defaults: { _controller: PCFundationBundle:Admin:jornadacensoedit }
    
pc_admin_jornada_censo_agregar:
    path:     /admin/jornadacenso/agregar/{meetingId}
    defaults: { _controller: PCFundationBundle:Admin:jornadacensodatos }

pc_admin_jornada_censo_registrar:
    path:     /admin/jornadacenso/agregar
    defaults: { _controller: PCFundationBundle:Admin:registrarcenso }
    methods:  POST

pc_admin_jornada_censo_add:
    path:     /admin/jornadacenso/add
    defaults: { _controller: PCFundationBundle:Admin:jornadacensoadd } 

pc_admin_jornada_censo_create:
    path:     /admin/jornadacenso/create
    defaults: { _controller: PCFundationBundle:Admin:jornadacensocreate } 
    methods:  POST
    
pc_admin_jornada_esterilizacion:
    path:     /admin/esterilizacion
    defaults: { _controller: PCFundationBundle:Admin:jornadaesteriliza } 
    
pc_admin_esterilizacion:
    path:     /admin/esteriliza/mas/{meetingId}/{controlAt}/{amount}
    defaults: { _controller: PCFundationBundle:Admin:esterilizacion } 
    
pc_admin_esterilizacion_add:
    path:   /admin/esterilizacion/add/{meetingId}
    defaults: {_controller: PCFundationBundle:Admin:esterilizacionAdd }

pc_admin_esterilizacion_update_list:
    path:   /admin/esterilizacion/update/{petId}/{meetingId}/{controlAt}/{amount}
    defaults: {_controller: PCFundationBundle:Admin:esterilizacionUpdate }

pc_admin_esterilizacion_create:
    path:   /admin/esterilizacion/create
    defaults: {_controller: PCFundationBundle:Admin:createesterilizacion }
    methods: POST

#--------------------------------------------------------------
#--- rutas del administrador para mascotas --------------------
#--------------------------------------------------------------

pc_admin_adopt_pet:
    path:     /admin/adopcion/
    defaults: { _controller: PCFundationBundle:Admin:adopcionview }

pc_admin_adopt_pet_info:
    path:     /admin/adopcion/info
    defaults: { _controller: PCFundationBundle:Admin:adopcioninfo }
    
pc_admin_adopt_pet_edit:
    path:     /admin/adopcion/edit
    defaults: { _controller: PCFundationBundle:Admin:adopcionedit }

pc_administrator_pet_add:
    path:     /admin/pet/add
    defaults: { _controller: PCFundationBundle:Admin:addpet }

pc_administrator_pet_create:
    path:     /admin/pet/create
    defaults: { _controller: PCFundationBundle:Admin:createpet }
    methods:  POST

pc_admin_pet_photo:
    path:     /admin/pet/photo
    defaults: { _controller: PCFundationBundle:Admin:upload }
    
pc_admin_pet_solicitudes:
    path: /admin/pet/solicitudes
    defaults: { _controller: PCFundationBundle:Admin:solicitudes}

pc_admin_aceptar_solicitud:
    path: /admin/pet/aceptar/{solicitudId}
    defaults: { _controller: PCFundationBundle:Admin:solaceptar}

pc_admin_pendiente_solicitud:
    path: /admin/pet/pendiente/{solicitudId}
    defaults: { _controller: PCFundationBundle:Admin:solpendiente}

pc_admin_rechazar_solicitud:
    path: /admin/pet/rechazar/{solicitudId}
    defaults: { _controller: PCFundationBundle:Admin:solrechazar}

pc_admin_pet_solicitudes_date:
    path: /admin/pet/solicitud/date/{userId}
    defaults: { _controller: PCFundationBundle:Admin:solicituddate}
 
pc_admin_adoptada_pet:
    path: /admin/adoptada/pet
    defaults: { _controller: PCFundationBundle:Admin:mascotadoptada}

#--------------------------------------------------------------
#--- rutas del administrador para Donativos -------------------
#--------------------------------------------------------------

pc_admin_donativ_recepcion:
    path: /admin/recepcion
    defaults: { _controller: PCFundationBundle:Admin:recepcion }

pc_admin_donativ_recepcion_add:
    path: /admin/recepcion/add
    defaults: { _controller: PCFundationBundle:Admin:recepcionadd }
    
pc_admin_donativ_add:
    path: /admin/donativ/add
    defaults: { _controller: PCFundationBundle:Admin:donativoadd }

pc_admin_donativ_create:
    path: /admin/donativ/create
    defaults: { _controller: PCFundationBundle:Admin:createDonative }
    methods: POST
    
pc_admin_donativ:
    path: /admin/donativ
    defaults: { _controller: PCFundationBundle:Admin:donativos }
    
#--------------------------------------------------------------
#--- rutas del administrador para eventos ---------------------
#--------------------------------------------------------------    
    
pc_administrator_eventos:
    path:     /admin/eventos
    defaults: { _controller: PCFundationBundle:Admin:eventos }

pc_administrator_eventos_add:
    path:     /admin/eventos/add
    defaults: { _controller: PCFundationBundle:Admin:eventosadd }

pc_administrator_eventos_create:
    path:     /admin/eventos/create
    defaults: { _controller: PCFundationBundle:Admin:eventocreate }
    methods:  POST

pc_administrator_evento_edit:
    path:     /admin/eventos/edit/{eventId}
    defaults: {_controller: PCFundationBundle:Admin:eventoedit }

pc_administrator_evento_update:
    path:     /admin/eventos/update/{eventId}
    defaults: {_controller: PCFundationBundle:Admin:eventUpdate }
    methods:  [POST, PUT]


pc_administrator_evento_delete:
    path:   /admin/eventos/delete/{eventId}
    defaults: {_controller: PCFundationBundle:Admin:eventoDelete }


#--------------------------------------------------------------
#--- rutas del administrador para creditos ---------------------
#--------------------------------------------------------------    
    
pc_administrator_credito_add:
    path:     /admin/creditoadd
    defaults: { _controller: PCFundationBundle:Admin:creditoadd }

pc_administrator_credito_create:
    path:     /admin/credito/create
    defaults: { _controller: PCFundationBundle:Admin:registrarCredito }
    methods: POST

pc_administrator_creditos:
    path:   /admin/creditos
    defaults: {_controller: PCFundationBundle:Admin:creditoinfo }

pc_administrator_creditos_cancelar:
    path:   /admin/creditos/cancel/{creditId}
    defaults: {_controller: PCFundationBundle:Admin:cancelarCredito }

pc_administrator_credito_fin:
    path:   /admin/creditofin
    defaults: {_controller: PCFundationBundle:Admin:creditofin }
