#--------------------------------------------------------------
#--- rutas de navegación     ----------------------------------
#--------------------------------------------------------------

pc_fundation_homepage:
    path:     /
    defaults: { _controller: PCFundationBundle:Main:index }

pc_fundation_comedogs:
    path:     /index/comedogs
    defaults: { _controller: PCFundationBundle:Main:comedogs }
 
pc_fundation_tapitas:
    path:     /index/tapitas
    defaults: { _controller: PCFundationBundle:Main:tapitas }
    
pc_fundation_adoptar:
    path:     /index/adoptar
    defaults: { _controller: PCFundationBundle:Main:adoptar }

pc_fundation_index:
    path:     /index
    defaults: { _controller: PCFundationBundle:Main:index }
    
pc_fundation_nosotros:
    path:     /nosotros
    defaults: { _controller: PCFundationBundle:Main:nosotros }

#--------------------------------------------------------------
#--- rutas del usuario ----------------------------------------
#--------------------------------------------------------------

pc_fundation_encuesta:
    path:     /encuesta
    defaults: { _controller: PCFundationBundle:Main:encuesta }
    
pc_user_encuesta:
    path:     /user/add
    defaults: { _controller: PCFundationBundle:User:add }

pc_user_create:
    path:     /user/create
    defaults: { _controller: PCFundationBundle:User:create }
    methods:  POST
    
#--------------------------------------------------------------
#--- rutas del administrador ----------------------------------
#--------------------------------------------------------------

pc_administrator_index:
    path:     /admin/
    defaults: { _controller: PCFundationBundle:Admin:index }

pc_administrator_login:
    path:     /admin/login
    defaults: { _controller: PCFundationBundle:Admin:login }
    
pc_administrator_logout:
    path:     /admin/logout
    defaults: { _controller: PCFundationBundle:Admin:logout }
    
pc_administrator_add:
    path:     /admin/add
    defaults: { _controller: PCFundationBundle:Admin:add }

pc_administrator_create:
    path:     /admin/create
    defaults: { _controller: PCFundationBundle:Admin:create }
    methods:  POST
    
pc_administrator_edit:
    path:     /admin/edit
    defaults: { _controller: PCFundationBundle:Admin:edit }
    
pc_administrator_update:
    path:     /admin/update/{id}
    defaults: { _controller: PCFundationBundle:Admin:update }   
    
#--------------------------------------------------------------
#--- rutas del administrador para censo -----------------------
#--------------------------------------------------------------

pc_admin_jornada_censo:
    path:     /admin/jornadacenso/view
    defaults: { _controller: PCFundationBundle:Admin:jornadacenso } 

pc_admin_jornada_censo_mas:
    path:     /admin/jornadacenso/mas
    defaults: { _controller: PCFundationBundle:Admin:jornadacensomas }

pc_admin_jornada_censo_edit:
    path:     /admin/jornadacenso/edit
    defaults: { _controller: PCFundationBundle:Admin:jornadacensoedit }
    
pc_admin_jornada_censo_agregar:
    path:     /admin/jornadacenso/agregar
    defaults: { _controller: PCFundationBundle:Admin:jornadacensodatos }

pc_admin_jornada_censo_add:
    path:     /admin/jornadacenso/add
    defaults: { _controller: PCFundationBundle:Admin:jornadacensoadd } 

pc_admin_jornada_censo_create:
    path:     /admin/jornadacenso/create
    defaults: { _controller: PCFundationBundle:Admin:jornadacensocreate } 
    methods:  POST
    
pc_admin_jornada_esterilizacion:
    path:     /admin/esterilizacion
    defaults: { _controller: PCFundationBundle:Admin:jornadaesteriliza } 
    
pc_admin_esterilizacion:
    path:     /admin/esteriliza/mas
    defaults: { _controller: PCFundationBundle:Admin:esterilizacion } 
    
pc_admin_esterilizacion_add:
    path:   /admin/esterilizacion/add
    defaults: {_controller: PCFundationBundle:Admin:esterilizacionAdd }

#--------------------------------------------------------------
#--- rutas del administrador para mascotas --------------------
#--------------------------------------------------------------

pc_admin_adopt_pet:
    path:     /admin/adopcion/
    defaults: { _controller: PCFundationBundle:Admin:adopcionview }

pc_administrator_pet_add:
    path:     /admin/pet/add
    defaults: { _controller: PCFundationBundle:Admin:addpet }

pc_administrator_pet_create:
    path:     /admin/pet/create
    defaults: { _controller: PCFundationBundle:Admin:createpet }
    methods:  POST

pc_admin_pet_photo:
    path:     /admin/pet/photo
    defaults: { _controller: PCFundationBundle:Admin:upload }
    
pc_admin_pet_solicitudes:
    path: /admin/pet/solicitudes
    defaults: { _controller: PCFundationBundle:Admin:solicitudes}

pc_admin_pet_solicitudes_date:
    path: /admin/pet/solicitud/date
    defaults: { _controller: PCFundationBundle:Admin:solicituddate}
 
pc_admin_adoptada_pet:
    path: /admin/adoptada/pet
    defaults: { _controller: PCFundationBundle:Admin:mascotadoptada}
