#--------------------------------------------------------------
#--- rutas de navegación     ----------------------------------
#--------------------------------------------------------------

pc_fundation_homepage:
    path:     /
    defaults: { _controller: PCFundationBundle:Main:index }

pc_fundation_comedogs:
    path:     /index/comedogs
    defaults: { _controller: PCFundationBundle:Main:comedogs }
 
pc_fundation_tapitas:
    path:     /index/tapitas
    defaults: { _controller: PCFundationBundle:Main:tapitas }
    
pc_fundation_adoptar:
    path:     /index/adoptar
    defaults: { _controller: PCFundationBundle:Main:adoptar }

pc_fundation_index:
    path:     /index
    defaults: { _controller: PCFundationBundle:Main:index }
    
pc_fundation_nosotros:
    path:     /nosotros
    defaults: { _controller: PCFundationBundle:Main:nosotros }

#--------------------------------------------------------------
#--- rutas del usuario ----------------------------------------
#--------------------------------------------------------------

pc_fundation_encuesta:
    path:     /encuesta
    defaults: { _controller: PCFundationBundle:Main:encuesta }
    
pc_user_encuesta:
    path:     /user/add
    defaults: { _controller: PCFundationBundle:User:add }

pc_user_create:
    path:     /user/create
    defaults: { _controller: PCFundationBundle:User:create }
    methods:  POST
    
#--------------------------------------------------------------
#--- rutas del administrador ----------------------------------
#--------------------------------------------------------------

pc_administrator_index:
    path:     /admin/
    defaults: { _controller: PCFundationBundle:Admin:index }

pc_administrator_pet_add:
    path:     /admin/pet/add
    defaults: { _controller: PCFundationBundle:Admin:addpet }

pc_administrator_pet_create:
    path:     /admin/pet/create
    defaults: { _controller: PCFundationBundle:Admin:createpet }
    methods:  POST
    
pc_administrator_add:
    path:     /admin/add
    defaults: { _controller: PCFundationBundle:Admin:add }

pc_administrator_create:
    path:     /admin/create
    defaults: { _controller: PCFundationBundle:Admin:create }
    methods:  POST
    
pc_administrator_edit:
    path:     /admin/edit/{id}
    defaults: { _controller: PCFundationBundle:Admin:edit }
    
pc_administrator_update:
    path:     /admin/update/{id}
    defaults: { _controller: PCFundationBundle:Admin:update }    
